<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    $cssCode .= <<<CSS

input[type="text"]::placeholder,
input[type="email"]::placeholder,
input[type="url"]::placeholder,
input[type="password"]::placeholder,
input[type="search"]::placeholder,
input[type="number"]::placeholder,
input[type="tel"]::placeholder,
input[type="range"]::placeholder,
input[type="date"]::placeholder,
input[type="month"]::placeholder,
input[type="week"]::placeholder,
input[type="time"]::placeholder,
input[type="datetime"]::placeholder,
input[type="datetime-local"]::placeholder,
input[type="color"]::placeholder,
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea::placeholder,
textarea,
.mainmenu-container ul ul .menu-item > a,
.mainmenu-container li a span,
.site-footer a,
.breadcrumb a,
.widget a,
.opal-custom-menu-inline .widget_nav_menu li ul a,
.c-body,
.blog article.type-post .more-link:hover,
.blog article.type-page .more-link:hover,
.archive article.type-post .more-link:hover,
.archive article.type-page .more-link:hover,
.search article.type-post .more-link:hover,
.search article.type-page .more-link:hover,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.column-item .post-inner .posted-on .entry-date,
.cart-collaterals .cart_totals th,
#payment .payment_methods li.woocommerce-notice,
#payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods li.woocommerce-info,
table.woocommerce-checkout-review-order-table th,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item:not(.radio-variable-item).button-variable-item .variable-item-span-button:after,
.elementor-nav-menu--dropdown a,
.elementor-tabs-h-align-flex-end .elementor-tabs-wrapper .elementor-tab-title,
.elementor-search-form--skin-minimal .elementor-search-form__icon,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title:not(:hover),
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title:not(.elementor-active),
.woocommerce-shipping-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.woocommerce-billing-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.opal-currency_switcher .list-currency button[type="submit"],
.select-selected,
.select-items div,
.opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit span:before {
  color: {$color_body}; }



.widget-area strong,
h1,
h2,
h3,
h4,
h5,
h6,
.opal-h1,
.page-title-bar .page-title,
.opal-h2,
.opal-h3,
.opal-h4,
.opal-h5,
.opal-h6,
blockquote,
.breadcrumb.current-item,
.breadcrumb span.current-item,
.breadcrumb *.current-item,
label,
th,
a,
.main-navigation .top-menu > li > a,
.main-navigation:not(.navigation-dark) .top-menu > li > a,
.breadcrumb,
h2.widget-title,
h2.widgettitle,
.c-heading,
fieldset legend,
.related-heading,
.author-wrapper .author-name,
.post-navigation .nav-title,
.search .entry-header a,
.search .site-content .page-title,
.site-header-account .login-form-title,
.comments-title,
.column-item .post-inner .entry-title a,
table.shop_table_responsive tbody th,
.site-header-cart .widget_shopping_cart p.total .woocommerce-Price-amount,
.site-header-cart .shopping_cart_nav p.total .woocommerce-Price-amount,
.filter-toggle,
.filter-close,
table.cart:not(.wishlist_table) th,
table.cart:not(.wishlist_table) .product-name a,
table.cart:not(.wishlist_table) .product-subtotal .woocommerce-Price-amount,
.cart-collaterals .cart_totals .order-total .woocommerce-Price-amount,
.cart-collaterals .cart_totals .amount,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info,
#payment .payment_methods > .wc_payment_method > label,
table.woocommerce-checkout-review-order-table .order-total .woocommerce-Price-amount,
table.woocommerce-checkout-review-order-table .product-name,
.woocommerce-billing-fields label,
.woocommerce-billing-fields > h3,
.cart th,
.shop_table th,
.woocommerce-account .woocommerce-MyAccount-content strong,
.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Price-amount,
.osf-sorting .display-mode button.active,
.osf-sorting .display-mode button:hover,
.woocommerce-Tabs-panel table.shop_attributes th,
#osf-accordion-container table.shop_attributes th,
.single-product div.product .product_meta .sku_wrapper,
.single-product div.product .product_meta .posted_in,
.single-product div.product .product_meta .tagged_as,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control],
.woosw-list table.woosw-content-items .woosw-content-item .woosw-content-item--add > a,
.woosw-area .woosw-inner .woosw-content .woosw-content-mid table.woosw-content-items .woosw-content-item .woosw-content-item--add > a,
.elementor-accordion .elementor-tab-title,
.elementor-featured-box-wrapper .elementor-featured-box-title,
.elementor-widget-image-box:not(:hover) .elementor-image-box-title,
.elementor-widget-opal-image-hotspots .elementor-accordion .elementor-tab-title,
.elementor-widget-opal-item-box .elementor-item-box-meta-inner:not(:hover) .elementor-item-box-name,
.elementor-price-table__currency,
.elementor-price-table__integer-part,
.elementor-price-table__feature-inner span.item-active,
.elementor-price-table__period,
.elementor-widget-opal-products-tabs .elementor-tab-title,
.elementor-progress-percentage,
.elementor-widget-progress .elementor-title,
.elementor-teams-wrapper .elementor-team-name:not(:hover) {
  color: {$color_heading}; }



.btn-link,
.elementor-element .elementor-button-link .elementor-button,
.button-link,
.more-link,
blockquote:before,
.main-navigation .top-menu > li:hover > a,
.main-navigation .top-menu > li:active > a,
.main-navigation .top-menu > li:focus > a,
.mainmenu-container ul ul .menu-item > a:hover,
.mainmenu-container ul ul .menu-item > a:active,
.mainmenu-container ul ul .menu-item > a:focus,
.mainmenu-container li.current-menu-parent > a,
.mainmenu-container .menu-item > a:hover,
.menu-toggle,
.site-header .header-group .search-submit:hover,
.site-header .header-group .search-submit:focus,
.error404 .error-404-bkg,
.error404 .sub-h2-1,
.breadcrumb a:hover,
.breadcrumb a:hover span,
.site-header-account > a:hover i,
.site-header-account > a:hover .text-account,
.site-header-account > a:hover .submenu-indicator,
.button-outline-primary,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.c-primary,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.entry-title a:hover,
.entry-meta a:hover,
body.single-post.opal-single-post-style .navigation .nav-link a:hover,
.opal-post-navigation-2 .post-navigation .nav-links .nav-previous a:hover:before,
.opal-post-navigation-2 .post-navigation .nav-links .nav-next a:hover:before,
.blog article.type-post .more-link,
.blog article.type-page .more-link,
.archive article.type-post .more-link,
.archive article.type-page .more-link,
.search article.type-post .more-link,
.search article.type-page .more-link,
.search .entry-header a:hover,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.site-header-account .account-links-menu li a:hover,
.site-header-account .account-dashboard li a:hover,
.opal-comment-4 .comment-content h1,
.opal-comment-4 .comment-content h2,
.opal-comment-4 .comment-content h3,
.opal-comment-4 .comment-content h4,
.opal-comment-4 .comment-content h5,
.opal-comment-4 .comment-content h6,
.comment-form a:hover,
#secondary .widget_product_categories ul li.current-cat > a,
.widget a:hover,
.widget_search button[type="submit"]:hover,
.widget_search button[type="submit"]:focus,
.opal-custom-menu-inline .widget ul li a:hover,
#secondary .elementor-widget-container h5:first-of-type,
.column-item .post-inner .entry-title a:hover,
.column-item.post-style-5 .post-inner .entry-title a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:focus,
.site-header-cart .shopping_cart_nav .product_list_widget li a:hover,
.site-header-cart .shopping_cart_nav .product_list_widget li a:focus,
.site-header-cart .woocommerce-mini-cart__empty-message:before,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a:hover,
.woocommerce-privacy-policy-link,
.opal-currency_switcher .list-currency button[type="submit"]:hover,
.opal-currency_switcher .list-currency li.active button[type="submit"],
ul.products li.product.osf-product-list .price,
ul.products li.product .posfed_in a:hover,
.select-items div:hover,
.single-product div.product .summary .price,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control]:hover,
.button-wrapper #chart-button,
#reviews .reviews-summary .review-summary-total .review-summary-result,
.link-comment,
#secondary section.widget .current-cat > a,
.widget_product_categories ul li a:hover,
.widget_rating_filter ul li a:hover,
.woocommerce-widget-layered-nav ul li a:hover,
.widget_product_brands ul li a:hover,
.widget_product_categories ul li.chosen a,
.widget_rating_filter ul li.chosen a,
.woocommerce-widget-layered-nav ul li.chosen a,
.widget_product_brands ul li.chosen a,
.product_list_widget a:hover,
.product_list_widget a:active,
.product_list_widget a:focus,
.woocommerce-product-list a:hover,
.woocommerce-product-list a:active,
.woocommerce-product-list a:focus,
.product-style-1 li.product .price,
.product-style-1 li.product .price ins,
.product-style-2 li.product:not(.otf-product-list) .price,
.product-style-2 li.product:not(.otf-product-list) .price ins,
.product-style-3 li.product .price,
.product-style-3 li.product .price ins,
.owl-theme.owl-carousel .owl-nav [class*='owl-']:hover:before,
.owl-theme .products .owl-nav [class*='owl-']:hover:before,
#secondary .elementor-widget-wp-widget-recent-posts a,
.contactform-content .form-title,
.elementor-widget-opal-countdown .elementor-countdown-digits,
.elementor-counter .elementor-icon-counter,
.elementor-counter .elementor-counter-number,
.elementor-counter .elementor-counter-number-prefix,
.elementor-counter .elementor-counter-number-suffix,
.elementor-featured-box-wrapper i,
.elementor-widget-heading .sub-title,
.elementor-widget-icon-box.elementor-view-framed:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-framed:not(:hover) .elementor-icon,
.elementor-widget-icon-box.elementor-view-default:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-default:not(:hover) .elementor-icon,
.elementor-widget-icon-box:hover .elementor-icon-box-title,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:not(:hover) i,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:not(:hover) .elementor-icon-list-text,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:hover i,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:hover .elementor-icon-list-text,
.elementor-widget-icon.elementor-view-default .elementor-icon,
.elementor-widget-icon.elementor-view-framed .elementor-icon,
.elementor-widget-image-box:hover .elementor-image-box-title,
.elementor-widget-opal-image-hotspots .elementor-accordion .elementor-tab-title.elementor-active,
.elementor-widget-opal-item-box .elementor-item-box-meta-inner:not(:hover) i,
.elementor-widget-opal-item-box .elementor-item-box-meta-inner:hover .elementor-item-box-name,
.elementor-widget-opal-item-box .elementor-item-box-meta-inner:hover i,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal .elementor-nav-menu a.elementor-sub-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item.highlighted,
.elementor-nav-menu--main .elementor-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item:hover,
.elementor-nav-menu--main .elementor-item:focus,
.elementor-nav-menu--main .current-menu-ancestor .elementor-item.has-submenu,
.elementor-nav-menu--popup .elementor-item.highlighted,
.elementor-nav-menu--popup .elementor-item.elementor-item-active,
.elementor-nav-menu--popup .elementor-item:hover,
.elementor-nav-menu--popup .elementor-item:focus,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a:hover,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) a:hover,
.elementor-nav-menu--dropdown:not(.mega-menu) a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) .has-submenu,
.elementor-widget-opal-phone:not(:hover) i,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-title,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-subtitle,
.elementor-widget-opal-phone:hover i,
.elementor-widget-opal-phone:hover .elementor-phone-title,
.elementor-widget-opal-phone:hover .elementor-phone-subtitle,
.portfolio .portfolio-content .entry-title a:hover,
.portfolio .entry-category a:hover,
.elementor-portfolio-style-overlay .portfolio .portfolio-content .entry-title a:hover,
.elementor-portfolio-style-overlay .portfolio .portfolio-content .entry-category a:hover,
.elementor-portfolio__filter:hover,
.single-portfolio-navigation .nav-link:hover span,
.elementor-button-default .elementor-button,
.elementor-widget-opal-product-categories .product-cats:hover,
.elementor-widget-opal-products-tabs .elementor-tab-title:hover,
.elementor-widget-opal-products-tabs .elementor-tab-title.elementor-active,
.elementor-tabs-h-align-flex-end .elementor-tabs-wrapper .elementor-tab-title.elementor-active,
.elementor-tabs-h-align-flex-end .elementor-tabs-wrapper .elementor-tab-title:hover,
.elementor-search-form .elementor-search-form__submit:hover,
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title.elementor-active,
.elementor-teams-wrapper .elementor-team-name:hover,
.elementor-teams-wrapper .elementor-team-job,
.elementor-teams-wrapper .team-icon-socials a:hover,
.elementor-widget-opal-testimonials-2 .elementor-testimonial-title,
.elementor-widget-opal-testimonials-2 .testimonials-decor,
.elementor-video-popup:not(:hover) .elementor-video-icons,
.elementor-video-popup:not(:hover) .elementor-video-title,
.header-button:hover i,
.header-button:hover .title,
.header-button:hover .count-text,
.header-button:hover .amount,
.header-button:hover .text-wishlist,
.woocommerce-MyAccount-navigation ul li.is-active a,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item.button-variable-item:not(.radio-variable-item):hover,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item.button-variable-item.selected:not(.radio-variable-item) {
  color: {$color_primary->toCss()}; }


.f-primary {
  fill: {$color_primary->toCss()}; }


.mp-level::-webkit-scrollbar-thumb,
.page-numbers:not(ul):not(.dots):hover,
.page-numbers:not(ul):not(.dots):focus,
.page-numbers.current:not(ul):not(.dots),
.cat-tags-links .tags-links a:hover,
.page-links .page-number,
.error404 .error-btn-bh a,
.opal-comment-form-2 .comment-form input[type="submit"],
.opal-comment-form-3 .comment-form input[type="submit"],
#secondary .widget_product_categories ul li.current-cat > a:before,
section.widget_price_filter .ui-slider .ui-slider-range,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.button-outline-primary:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.button-outline-primary.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.show > .button-outline-primary.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.bg-primary,
.owl-theme.owl-carousel .owl-dots .owl-dot:hover span,
.owl-theme.owl-carousel .owl-dots .owl-dot.active span,
.owl-theme .products .owl-dots .owl-dot:hover span,
.owl-theme .products .owl-dots .owl-dot.active span,
.effect-skew:before,
.elementor-accordion .elementor-tab-title.elementor-active .elementor-accordion-icon,
.elementor-widget-divider .elementor-divider-separator:before,
.elementor-widget-heading .elementor-heading-title:before,
.elementor-widget-heading .elementor-heading-title:after,
.elementor-widget-heading .elementor-widget-container:before,
.elementor-widget-heading .elementor-widget-container:after,
.elementor-widget-icon-box.elementor-view-stacked:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-stacked:not(:hover) .elementor-icon,
.elementor-widget-icon.elementor-view-stacked .elementor-icon,
.elementor-widget-opal-image-hotspots .scrollbar-inner > .scroll-element .scroll-bar,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon,
.elementor-widget-opal-image-gallery .gallery-item-overlay,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:before,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:after,
.elementor-nav-menu--main.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:not(:hover):before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:hover:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:after,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:after,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item:hover:before,
.elementor-nav-menu--main.elementor-nav-menu--layout-vertical-absolute .vertical-heading,
.e--pointer-dot .elementor-item:before,
.e--pointer-underline .elementor-item:before,
.e--pointer-underline .elementor-item:after,
.single-portfolio-summary .pbr-social-share a:hover,
.column-item .post-inner .post-author:before,
.column-item.post-style-5 .post-inner .entry-title:hover:before,
.elementor-widget-opal-products-tabs .elementor-tab-title:before,
.elementor-widget-opal-testimonials .layout_2 .item-box:hover,
.elementor-widget-text-editor .elementor-text-editor p:before,
.elementor-widget-text-editor .elementor-text-editor p:after,
.elementor-timeline-carousel .timeline-carosuel-item .timeline-number,
.elementor-timeline-carousel .timeline-carosuel-item:hover .timeline-number,
.elementor-timeline-carousel .timeline-carosuel-item.timeline-item-activate .timeline-number,
.timeline-item .timeline-number,
.elementor-timeline-view-vertical .timeline-number,
.header-button .count,
.header-button:not(:hover),
.notification-added-to-cart .ns-content,
#payment .place-order .button:hover,
form.register .button[type="submit"]:hover,
.opal-label-sale-circle li.product .onsale:before,
#yith-quick-view-modal ::-webkit-scrollbar-thumb,
#yith-quick-view-modal :window-inactive::-webkit-scrollbar-thumb,
.woocommerce-tabs ul.tabs li a:after,
.single-product .single_add_to_cart_button,
.single-product button.disabled.single_add_to_cart_button[type="submit"],
.title-heading:after,
.woocommerce-widget-layered-nav ul li.chosen a.osf-label-type,
.widget_price_filter .ui-slider .ui-slider-handle,
.widget_price_filter .ui-slider .ui-slider-range,
.handheld-footer-bar .cart .footer-cart-contents .count,
.product-style-1 li.product .yith-wcqv-button,
.product-style-1 li.product .yith-wcwl-add-to-wishlist > div > a,
.product-style-1 li.product .compare,
.product-style-1 li.product a[class*="product_type_"],
.product-style-2 li.product:not(.otf-product-list) .yith-wcqv-button,
.product-style-2 li.product:not(.otf-product-list) .yith-wcwl-add-to-wishlist > div > a,
.product-style-2 li.product:not(.otf-product-list) .compare,
.product-style-2 li.product:not(.otf-product-list) a[class*="product_type_"]:hover,
.product-style-2 li.product:not(.otf-product-list) a.loading[class*="product_type_"],
.product-style-3 li.product .yith-wcqv-button,
.product-style-3 li.product .yith-wcwl-add-to-wishlist > div > a,
.product-style-3 li.product .compare,
.product-style-3 li.product a[class*="product_type_"]:hover,
.product-style-3 li.product a.loading[class*="product_type_"],
.shop-action .wooscp-btn,
.shop-action .woosq-btn,
.shop-action .woosw-btn {
  background-color: {$color_primary->toCss()}; }



.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.form-control:focus,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
.opal-comment-form-2 .comment-form input[type="submit"],
.opal-comment-form-3 .comment-form input[type="submit"],
#secondary .widget_product_categories ul li.current-cat > a:before,
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.button-outline-primary:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.button-outline-primary:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.button-outline-primary.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.show > .button-outline-primary.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.b-primary,
.elementor-widget-icon-box.elementor-view-framed:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-framed:not(:hover) .elementor-icon,
.elementor-widget-icon.elementor-view-default .elementor-icon,
.elementor-widget-icon.elementor-view-framed .elementor-icon,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active:before,
.e--pointer-framed .elementor-item.elementor-item-active:before,
.e--pointer-framed .elementor-item.elementor-item-active:after,
.e--pointer-framed .elementor-item:before,
.e--pointer-framed .elementor-item:after,
.elementor-nav-menu--main > .elementor-nav-menu,
.elementor-nav-menu--main .elementor-nav-menu ul,
.mega-menu-item,
ul.elementor-price-table__features-list,
.elementor-widget-opal-product-deals .woocommerce-product-list li .inner,
.elementor-widget-opal-products.elementor-product-list-border-style.elementor-product-list-style-2 .woocommerce-product-list li .inner,
.elementor-search-form__container:not(.elementor-search-form--full-screen),
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title.elementor-active,
.elementor-teams-wrapper .team-icon-socials a:hover,
.elementor-widget-opal-testimonials .layout_7 .elementor-testimonial-image img:hover,
.elementor-widget-opal-testimonials .layout_7 .elementor-testimonial-dot-image.active img,
.elementor-timeline-carousel .timeline-carosuel-item:hover .timeline-number,
.elementor-timeline-carousel .timeline-carosuel-item.timeline-item-activate .timeline-number,
.elementor-video-popup:not(:hover) .elementor-video-icons,
.elementor-video-popup:not(:hover) .elementor-video-title,
#payment .place-order .button:hover,
form.register .button[type="submit"]:hover,
.single-product div.product .woocommerce-product-gallery .flex-control-thumbs li img.flex-active,
.single-product div.product .woocommerce-product-gallery .flex-control-thumbs li:hover img,
.single-product .single_add_to_cart_button,
.single-product button.disabled.single_add_to_cart_button[type="submit"],
.woocommerce-widget-layered-nav ul li.chosen a.osf-label-type,
.osf-product-deal .woocommerce-product-list .opal-countdown .day,
.otf-product-recently-content li:hover .product-thumbnail img,
.product-style-3 li.product a[class*="product_type_"] {
  border-color: {$color_primary->toCss()}; }


.main-navigation .top-menu > li ul {
  border-top-color: {$color_primary->toCss()}; }


.main-navigation .top-menu > li:hover:before,
.main-navigation .top-menu > li:active:before,
.main-navigation .top-menu > li:focus:before,
.main-navigation .top-menu > li.menu-item-has-children:before,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.menu-item-has-children:before,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.has-mega-menu:before {
  border-bottom-color: {$color_primary->toCss()}; }


.cat-tags-links .tags-links a:hover:before {
  border-right-color: {$color_primary->toCss()}; }



.btn-link:focus,
.elementor-element .elementor-button-link .elementor-button:focus,
.btn-link:hover,
.elementor-element .elementor-button-link .elementor-button:hover,
.button-link:focus,
.more-link:focus,
.button-link:hover,
.more-link:hover,
a:hover,
a:active,
.elementor-video-popup:hover .elementor-video-icons,
.elementor-video-popup:hover .elementor-video-title {
  color: {$color_primary_hover->toCss()}; }


.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.header-button:hover,
.single-product .single_add_to_cart_button:hover,
.single-product button.disabled.single_add_to_cart_button[type="submit"]:hover,
.product-style-1 li.product .yith-wcqv-button:hover,
.product-style-1 li.product .yith-wcwl-add-to-wishlist > div > a:hover,
.product-style-1 li.product .compare:hover,
.product-style-2 li.product:not(.otf-product-list) .yith-wcqv-button:hover,
.product-style-2 li.product:not(.otf-product-list) .yith-wcwl-add-to-wishlist > div > a:hover,
.product-style-2 li.product:not(.otf-product-list) .compare:hover,
.product-style-3 li.product .yith-wcqv-button:hover,
.product-style-3 li.product .yith-wcwl-add-to-wishlist > div > a:hover,
.product-style-3 li.product .compare:hover,
.shop-action .wooscp-btn:hover,
.shop-action .woosq-btn:hover,
.shop-action .woosw-btn:hover {
  background-color: {$color_primary_hover->toCss()}; }


.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.elementor-video-popup:hover .elementor-video-icons,
.elementor-video-popup:hover .elementor-video-title,
.single-product .single_add_to_cart_button:hover,
.single-product button.disabled.single_add_to_cart_button[type="submit"]:hover {
  border-color: {$color_primary_hover->toCss()}; }



.error404 .sub-h2-2,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.c-secondary,
.author-wrapper .author-name h6,
.contactform-content button.mfp-close {
  color: {$color_secondary->toCss()}; }


.f-secondary {
  fill: {$color_secondary->toCss()}; }



.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.mailchimp-button-outline_secondary button:hover,
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.mailchimp-button-outline_secondary button:active,
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.mailchimp-button-outline_secondary button.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.bg-secondary,
#secondary .elementor-widget-wp-widget-categories a:before {
  background-color: {$color_secondary->toCss()}; }


.secondary-border .search-form input[type="text"],
.secondary-border .search-form input[type="text"]:focus,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.b-secondary {
  border-color: {$color_secondary->toCss()}; }



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.opal-archive-style-4.blog .site-main,
.opal-archive-style-4.archive .site-main,
.opal-default-content-layout-2cr .site-content .wrap,
.site-footer .widget-area,
.opal-comment-form-2 .comment-form,
.opal-comment-form-3 .comment-form,
.opal-comment-form-4 .comment-form,
.opal-comment-form-6 .comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
[data-elementor-columns],
.single-portfolio-summary .single-portfolio-summary-inner,
.opal-canvas-filter.top .opal-canvas-filter-wrap,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone,
.woocommerce-cart .woocommerce,
.woocommerce-billing-fields .woocommerce-billing-fields__field-wrapper,
.woocommerce-MyAccount-content form[class^="woocommerce-"],
.woocommerce-columns--addresses,
form.track_order,
.woocommerce-account .woocommerce,
.woocommerce-account .woocommerce .u-columns.woocommerce-Addresses,
.woocommerce-Addresses,
.woocommerce-address-fields__field-wrapper,
ul.products,
.osf-sorting,
.single-product div.product,
.single-product div.product .woocommerce-product-gallery .flex-control-thumbs {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.col-4,
.opal-comment-form-2 .comment-form .comment-form-author,
.opal-comment-form-3 .comment-form .comment-form-author,
.opal-comment-form-2 .comment-form .comment-form-email,
.opal-comment-form-3 .comment-form .comment-form-email,
.opal-comment-form-2 .comment-form .comment-form-url,
.opal-comment-form-3 .comment-form .comment-form-url,
[data-elementor-columns-mobile="3"] .column-item,
.col-5,
.col-6,
.opal-comment-form-4 .comment-form .comment-form-author,
.opal-comment-form-4 .comment-form .comment-form-email,
.opal-comment-form-4 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .comment-form-author,
.opal-comment-form-6 .comment-form .comment-form-email,
[data-elementor-columns-mobile="2"] .column-item,
.single-product.opal-comment-form-2 .comment-form-author,
.single-product.opal-comment-form-3 .comment-form-author,
.single-product.opal-comment-form-2 .comment-form-email,
.single-product.opal-comment-form-3 .comment-form-email,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.related-posts .column-item,
.site-footer .widget-area .widget-column,
.opal-comment-form-2 .comment-form .logged-in-as,
.opal-comment-form-3 .comment-form .logged-in-as,
.opal-comment-form-2 .comment-form .comment-notes,
.opal-comment-form-3 .comment-form .comment-notes,
.opal-comment-form-2 .comment-form .comment-form-comment,
.opal-comment-form-3 .comment-form .comment-form-comment,
.opal-comment-form-2 .comment-form .form-submit,
.opal-comment-form-3 .comment-form .form-submit,
.opal-comment-form-4 .comment-form .logged-in-as,
.opal-comment-form-4 .comment-form .comment-notes,
.opal-comment-form-4 .comment-form .comment-form-comment,
.opal-comment-form-4 .comment-form .form-submit,
.opal-comment-form-6 .comment-form .logged-in-as,
.opal-comment-form-6 .comment-form .comment-notes,
.opal-comment-form-6 .comment-form .comment-form-comment,
.opal-comment-form-6 .comment-form .comment-form-url,
.opal-comment-form-6 .comment-form .form-submit,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.single-portfolio-summary .single-portfolio-summary-inner .single-portfolio-summary-meta-title,
.single-portfolio-summary .single-portfolio-summary-meta,
.single-portfolio-summary .single-portfolio-summary-content,
.single-portfolio-summary.col-lg-5 .single-portfolio-summary-meta,
form.track_order p.single-portfolio-summary.form-row-first .single-portfolio-summary-meta,
form.track_order p.single-portfolio-summary.form-row-last .single-portfolio-summary-meta,
.single-portfolio-summary.col-lg-5 .single-portfolio-summary-content,
form.track_order p.single-portfolio-summary.form-row-first .single-portfolio-summary-content,
form.track_order p.single-portfolio-summary.form-row-last .single-portfolio-summary-content,
.elementor-single-product .single-product div.product .entry-summary,
.woocommerce-cart .cart-empty,
.woocommerce-cart .return-to-shop,
.woocommerce-billing-fields .form-row-wide,
.woocommerce-MyAccount-content form[class^="woocommerce-"] > *:not(fieldset),
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-wide,
#customer_details [class*='col'],
.columns-1 ul.products li.product,
.columns-1 ul.products > li,
.col,
body #secondary,
.mfp-content .comment-form-rating,
.opal-canvas-filter.top .opal-canvas-filter-wrap section,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone .woof_container,
.columns-5 ul.products li.product,
.columns-5 ul.products > li,
.woocommerce-product-list.boxed,
.woocommerce-product-list.skin-border-box li .inner,
.woocommerce-product-list.skin-line-right li .inner,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.columns-6 ul.products li.product,
.columns-6 ul.products > li,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.elementor-timeline-view-vertical .timeline-thumbnail,
.elementor-timeline-view-vertical .timeline-content,
.woocommerce-billing-fields .form-row-first,
.woocommerce-billing-fields .form-row-last,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-first,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-last,
ul.products li.product,
.columns-2 ul.products li.product,
.columns-2 ul.products > li,
.columns-3 ul.products li.product,
.columns-3 ul.products > li,
.columns-4 ul.products li.product,
.columns-4 ul.products > li,
.opal-content-layout-2cl .columns-3 ul.products li.product,
.opal-content-layout-2cl .columns-3 ul.products > li,
.opal-content-layout-2cr .columns-3 ul.products li.product,
.opal-content-layout-2cr .columns-3 ul.products > li,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion + .opal-image-hotspots-container,
.cart-collaterals .cross-sells,
.woocommerce-columns--addresses .woocommerce-column,
form.track_order p:first-of-type,
.woocommerce-account .woocommerce-MyAccount-navigation,
.woocommerce-account .woocommerce-MyAccount-content,
.woocommerce-address-fields__field-wrapper .form-row,
.woocommerce-product-carousel ul.products li.product,
.osf-sorting .woocommerce-message,
.osf-sorting .woocommerce-notice,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.col-md-4,
[data-elementor-columns-tablet="3"] .column-item,
.col-md-5,
.opal-default-content-layout-2cr #secondary,
.osf-sorting .osf-sorting-group,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.col-md-7,
.opal-default-content-layout-2cr #primary,
.osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.woocommerce-cart-form,
.cart-collaterals,
form.track_order p.form-row-first,
form.track_order p.form-row-last,
form.track_order p:last-of-type,
.single-product div.product .entry-summary,
.single-product div.product .images,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
[data-elementor-columns="6"] .column-item,
.col-lg-3,
[data-elementor-columns="4"] .column-item,
.col-lg-4,
.opal-default-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
[data-elementor-columns="3"] .column-item,
.col-lg-5,
.col-lg-6,
[data-elementor-columns="2"] .column-item,
.col-lg-7,
.col-lg-8,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group + .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
[data-elementor-columns="1"] .column-item,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor,
.opal-canvas-filter.top,
.otf-product-recently-content .widget_recently_viewed_products {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 1140px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $border_radius, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.scrollup,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-element .elementor-button-primary .elementor-button {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.scrollup:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.scrollup:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.active.scrollup,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.show > .dropdown-toggle.scrollup,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $border_radius, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
h1,
h2,
h3,
h4,
h5,
h6,
.opal-h1,
.page-title-bar .page-title,
.opal-h2,
.opal-h3,
.opal-h4,
.opal-h5,
.opal-h6,
.author-wrapper .author-name,
.post-navigation .nav-subtitle,
.post-navigation .nav-title,
.error404 .error-404-bkg,
.error404 .error-404-subtitle h2,
h2.widget-title,
h2.widgettitle,
#secondary .elementor-widget-container h5:first-of-type,
.contactform-content .form-title,
.elementor-widget-opal-item-box .elementor-item-box-name,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title,
.elementor-teams-wrapper .elementor-team-name,
.elementor-teams-wrapper .elementor-team-job,
.elementor-video-title,
.osf-product-deal .woocommerce-product-list .opal-countdown {
    {$heading_css}
}


CSS;
    return $cssCode;
}
